"""Behavior-preserving tidying of Python source.

Today this does one thing: it removes trailing whitespace and makes sure a
file ends in exactly one newline. That is the only beautification built so far;
`burnish languages` says what else is written down and not yet built.

THE GUARD

Lines whose break sits inside a multi-line string are never touched, because
trailing spaces there are part of the string. As a second, independent guard,
every tidied file is parsed before and after; if the two syntax trees differ at
all, the file is left alone. Nothing is ever guessed to be safe.

LINE ENDINGS AND ENCODING

A file is read as bytes and must be valid UTF-8 and parse, or it is skipped
with a note (never a crash). Each line keeps the ending it had (CRLF, LF or a
mix), so only the trailing spaces change. A file with a leading BOM, or whose
first lines say "DO NOT EDIT" or "Generated by" (or "@generated", "autogenerated"), is
left alone, and so is anything in an environment, vendor, generated or build directory
(see `burnish.files`). A test file, test setting, CI file or Ghost file is never tidied
either, not even by whitespace: Warden and the Judge treat every change to one as the
loop grading its own work, and the Judge turns the whole finish away.

This module returns text. Writing it is Warden's job, behind a grant, a green
suite before and after, and a re-inspection by Ghost Tools.
"""

from __future__ import annotations

import ast
import io
import tokenize
from pathlib import Path
from typing import Optional

from warden.models import FileEdit

from .textsafe import clean
from .files import dominant_ending, is_protected, looks_generated, python_files, read_strict, split_endings

_BOM = "\ufeff"
_UNPARSEABLE = (SyntaxError, ValueError, RecursionError, MemoryError, tokenize.TokenError)


def tidy_source(source: str) -> Optional[str]:
    """The tidied text, or None if tidying would change the program or nothing needs tidying."""
    return _tidy(source)[0]


def _tidy(source: str) -> tuple[Optional[str], str]:
    """The tidied text (or None) and, when the file was left alone for a reason worth telling, the reason."""
    if not source.strip():
        return None, ""
    if source.startswith(_BOM):
        return None, "starts with a byte order mark"
    lines, endings = split_endings(source)
    try:
        inside_strings = _lines_ending_inside_a_string("\n".join(lines))
        before = ast.dump(ast.parse(source))
    except _UNPARSEABLE + (IndentationError,):
        return None, "does not parse"
    kept = [line if number in inside_strings else line.rstrip(" \t") for number, line in enumerate(lines, start=1)]
    while kept and not kept[-1].strip():
        kept.pop()
    if not kept:
        return None, ""
    last = endings[len(kept) - 1] if len(kept) - 1 < len(endings) else dominant_ending(source)
    tidied = "".join(line + ending for line, ending in zip(kept[:-1], endings)) + kept[-1] + last
    if tidied == source:
        return None, ""
    try:
        unchanged = before == ast.dump(ast.parse(tidied))
    except _UNPARSEABLE:
        return None, "would not parse after tidying"
    return (tidied, "") if unchanged else (None, "tidying would change the syntax tree")


def _lines_ending_inside_a_string(source: str) -> set[int]:
    """Line numbers whose line break belongs to a multi-line string, so trailing spaces there are data."""
    protected: set[int] = set()
    string_kinds = {tokenize.STRING, getattr(tokenize, "FSTRING_MIDDLE", tokenize.STRING)}
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type in string_kinds and token.end[0] > token.start[0]:
            protected.update(range(token.start[0], token.end[0]))
    return protected


def tidy_edits(root: Path, notes: Optional[list[str]] = None) -> list[FileEdit]:
    """One edit per Python file under `root` that tidying changes without changing the program.

    A file that cannot be read, decoded or parsed is skipped, and `notes` (if given) says how many and why.
    """
    root = Path(root).resolve()
    edits: list[FileEdit] = []
    skipped: list[str] = []
    for path in python_files(root):
        relative = path.relative_to(root).as_posix()
        if is_protected(relative):
            continue
        try:
            source = read_strict(path)
        except (OSError, ValueError):
            skipped.append(f"{relative} (not valid UTF-8 or unreadable)")
            continue
        if looks_generated(source):
            continue
        tidied, reason = _tidy(source)
        if reason:
            skipped.append(f"{relative} ({reason})")
        if tidied is not None:
            edits.append(FileEdit(path=relative, kind="write", new=tidied, old=source))
    if skipped and notes is not None:
        notes.append(f"Left {len(skipped)} Python file(s) untidied: {_names(skipped)}.")
    return edits


def _names(skipped: list[str]) -> str:
    """The first few skipped files for a note, with names made safe to print."""
    shown = "; ".join(clean(item, 120) for item in skipped[:5])
    return shown + (f"; and {len(skipped) - 5} more" if len(skipped) > 5 else "")
