"""Reading files safely and finding the ones Burnish may look at.

Four small jobs live here because the tidy, the narrative and the finisher all
need them and must agree:

  * which directories are somebody else's code (environments, vendored copies,
    generated code, build output) and are never walked,
  * which files decide whether a change is acceptable (tests, test settings, CI)
    and are never proposed for an edit,
  * how to find the README in its own format, whatever case its name is in,
  * how to read bytes strictly as UTF-8 and remember the line-ending style, so a
    file is written back the way it was found.

Nothing here writes.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Iterator, Optional

__all__ = ["SKIPPED_DIRS", "GENERATED_MARKERS", "README_NAMES", "MARKDOWN_SUFFIXES", "python_files",
           "read_strict", "looks_generated", "is_protected", "find_readme", "readme_is_markdown", "dominant_ending", "split_endings"]

#: Directories that hold code the target does not own, or output it can rebuild. The first
#: row mirrors what Warden refuses to touch (its forbidden and vendored directories); the
#: rest are extra. Warden's list is copied here, not imported: Burnish imports Warden's data
#: shapes and nothing of its guard. A change to Warden's list needs a change here.
SKIPPED_DIRS = frozenset({
    ".git", ".hg", ".svn", ".tox", ".eggs", ".venv", "venv", "env", "node_modules", "vendor",
    "vendored", "third_party", "thirdparty", "external", "extern", "generated", "gen",
    "site-packages", "build", "dist", "__pycache__", ".mypy_cache", ".pytest_cache",
    ".ruff_cache", "target",
})

#: Words in the first ten lines that say a file is generated or not for hand editing
#: (lower case; Warden's list, copied).
GENERATED_MARKERS = ("do not edit", "generated by", "auto-generated", "autogenerated", "@generated")

#: Files that decide whether a change is acceptable. Warden refuses to let the loop edit them and
#: the Judge rejects a run that does, even for a whitespace-only change. Names are compared in lower case.
_PROTECTED_NAMES = frozenset({
    "conftest.py", "pytest.ini", "tox.ini", "setup.cfg", "pyproject.toml", "noxfile.py", ".coveragerc",
    "makefile", "tests.py", "test.py", ".gitlab-ci.yml", ".travis.yml", "azure-pipelines.yml",
    "jenkinsfile", "appveyor.yml", "bitbucket-pipelines.yml", ".drone.yml",
})
_PROTECTED_DIRS = frozenset({"tests", "test", "testing", ".github", ".circleci", ".buildkite", ".gitlab"})

#: README file names in the order they are preferred. Matching ignores case.
README_NAMES = ("readme", "readme.md", "readme.markdown", "readme.rst", "readme.txt")

#: The only README formats Burnish may add its generated section to.
MARKDOWN_SUFFIXES = (".md", ".markdown")

_LINE_END = re.compile(r"(\r\n|\n|\r)")


def _skipped(name: str) -> bool:
    return name.lower() in SKIPPED_DIRS or name.lower().endswith(".egg-info")


def python_files(root: Path) -> Iterator[Path]:
    """Every Python file under `root` that is the target's own, in path order. Links are not followed."""
    root = Path(root)
    for here, dirs, names in os.walk(root, followlinks=False):
        dirs[:] = sorted(d for d in dirs if not _skipped(d))
        for name in sorted(names):
            path = Path(here) / name
            if name.endswith(".py") and path.is_file() and not path.is_symlink():
                yield path


def read_strict(path: Path) -> str:
    """The file's text exactly as written (line endings and any BOM kept), or ValueError if it is not valid UTF-8."""
    try:
        return Path(path).read_bytes().decode("utf-8")
    except UnicodeDecodeError as error:
        raise ValueError(f"{Path(path).name} is not valid UTF-8") from error


def looks_generated(text: str) -> bool:
    """True when the first ten lines say the file is generated or not to be edited by hand."""
    head = "\n".join(text.split("\n", 10)[:10]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def is_protected(relative: str) -> bool:
    """True for a path that decides whether a change is acceptable: a test, test settings, CI, or a Ghost file.

    The same files Warden and the Judge protect, compared without regard to case.
    """
    parts = [part for part in relative.replace("\\", "/").lower().split("/") if part not in {"", "."}]
    if not parts:
        return False
    name = parts[-1]
    return (name in _PROTECTED_NAMES or name.startswith(("test_", ".ghost_")) or name.endswith(("_test.py", "_tests.py"))
            or any(part.startswith(".ghost_") for part in parts) or bool(_PROTECTED_DIRS.intersection(parts[:-1])))


def find_readme(root: Path) -> Optional[Path]:
    """The README in `root` itself, found ignoring case, preferring README, .md, .markdown, .rst, .txt."""
    try:
        entries = [p for p in Path(root).iterdir() if p.is_file()]
    except OSError:
        return None
    for wanted in README_NAMES:
        match = sorted(p for p in entries if p.name.lower() == wanted)
        if match:
            return match[0]
    return None


def readme_is_markdown(path: Path) -> bool:
    """True when the README is a Markdown file, the one format a generated section can be added to."""
    return Path(path).suffix.lower() in MARKDOWN_SUFFIXES


def split_endings(text: str) -> tuple[list[str], list[str]]:
    """The lines of `text` and the line ending that follows each one (one fewer ending than lines)."""
    parts = _LINE_END.split(text)
    return parts[0::2], parts[1::2]


def dominant_ending(text: str) -> str:
    """The line ending most used in `text`: CRLF only when it outnumbers the rest, otherwise LF."""
    crlf = text.count("\r\n")
    lf = text.count("\n") - crlf
    cr = text.count("\r") - crlf
    return "\r\n" if crlf > lf and crlf > cr else ("\r" if cr > lf and cr > crlf else "\n")
