"""Reading files safely and finding the ones Burnish may look at.

Three small jobs live here because the tidy, the narrative and the finisher all
need them and must agree:

  * which directories are somebody else's code (environments, vendored copies,
    build output) and are never walked,
  * how to find the README in its own format, whatever case its name is in,
  * how to read bytes strictly as UTF-8 and remember the line-ending style, so a
    file is written back the way it was found.

Nothing here writes.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Iterator, Optional

__all__ = ["SKIPPED_DIRS", "README_NAMES", "MARKDOWN_SUFFIXES", "python_files", "read_strict",
           "looks_generated", "find_readme", "readme_is_markdown", "dominant_ending", "split_endings"]

#: Directories that hold code the target does not own, or output it can rebuild.
SKIPPED_DIRS = frozenset({
    ".git", ".hg", ".svn", ".tox", ".eggs", ".venv", "venv", "env", "node_modules", "vendor",
    "vendored", "third_party", "site-packages", "build", "dist", "__pycache__", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", "target",
})

#: README file names in the order they are preferred. Matching ignores case.
README_NAMES = ("readme", "readme.md", "readme.markdown", "readme.rst", "readme.txt")

#: The only README formats Burnish may add its generated section to.
MARKDOWN_SUFFIXES = (".md", ".markdown")

_GENERATED = re.compile(r"do not edit|generated by", re.I)
_LINE_END = re.compile(r"(\r\n|\n|\r)")


def _skipped(name: str) -> bool:
    return name.lower() in SKIPPED_DIRS or name.lower().endswith(".egg-info")


def python_files(root: Path) -> Iterator[Path]:
    """Every Python file under `root` that is the target's own, in path order. Links are not followed."""
    root = Path(root)
    for here, dirs, names in os.walk(root, followlinks=False):
        dirs[:] = sorted(d for d in dirs if not _skipped(d))
        for name in sorted(names):
            path = Path(here) / name
            if name.endswith(".py") and path.is_file() and not path.is_symlink():
                yield path


def read_strict(path: Path) -> str:
    """The file's text exactly as written (line endings and any BOM kept), or ValueError if it is not valid UTF-8."""
    try:
        return Path(path).read_bytes().decode("utf-8")
    except UnicodeDecodeError as error:
        raise ValueError(f"{Path(path).name} is not valid UTF-8") from error


def looks_generated(text: str) -> bool:
    """True when the first ten lines say the file is generated or not to be edited by hand."""
    return any(_GENERATED.search(line) for line in text.split("\n", 10)[:10])


def find_readme(root: Path) -> Optional[Path]:
    """The README in `root` itself, found ignoring case, preferring README, .md, .markdown, .rst, .txt."""
    try:
        entries = [p for p in Path(root).iterdir() if p.is_file()]
    except OSError:
        return None
    for wanted in README_NAMES:
        match = sorted(p for p in entries if p.name.lower() == wanted)
        if match:
            return match[0]
    return None


def readme_is_markdown(path: Path) -> bool:
    """True when the README is a Markdown file, the one format a generated section can be added to."""
    return Path(path).suffix.lower() in MARKDOWN_SUFFIXES


def split_endings(text: str) -> tuple[list[str], list[str]]:
    """The lines of `text` and the line ending that follows each one (one fewer ending than lines)."""
    parts = _LINE_END.split(text)
    return parts[0::2], parts[1::2]


def dominant_ending(text: str) -> str:
    """The line ending most used in `text`: CRLF only when it outnumbers the rest, otherwise LF."""
    crlf = text.count("\r\n")
    lf = text.count("\n") - crlf
    cr = text.count("\r") - crlf
    return "\r\n" if crlf > lf and crlf > cr else ("\r" if cr > lf and cr > crlf else "\n")
