"""The second red team: Burnish must never hand Warden a finish that the Judge or Warden will turn away.

A rejected finish puts everything back, so every test here is about an edit Burnish should not have proposed,
a README line it should not have written, or marker handling that damaged what the author wrote.
"""

import re
from pathlib import Path

import pytest
from warden.authorization import grant
from warden.guard import is_protected, is_vendored, violation
from warden.roles import Facts
from warden.suite import SuiteRun

from burnish import claims
from burnish.claims import absolutes, judge, unchecked_mentions
from burnish.finisher import Burnish
from burnish.marked import BEGIN, END, find_block, has_heading
from burnish.narrative import inspect_tree

FACTS = Facts(suite=SuiteRun(ran=True, passed=5), remaining=(), cycles=1)
DIRTY = '"""m."""\n\nVALUE = 1   \n'
#: Ghost Tools' own pattern for a claim about the number of tests (doc_test_count_drift), copied.
GHOST_TRIGGER = re.compile(r"\b(\d+)\s+tests?\b(?=\s*[,.]|\s+(?:passing|passed|collected))", re.I)


def _write(root: Path, rel: str, text: str | bytes = DIRTY) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text if isinstance(text, bytes) else text.encode("utf-8"))


def _tree(root: Path, readme: str | bytes | None = "# demo\n\nIntro.\n") -> None:
    _write(root, "pkg/ok.py")
    _write(root, "pyproject.toml", '[project]\nname = "demo"\nversion = "0.0.1"\n')
    if readme is not None:
        _write(root, "README.md", readme)


def _finish(root: Path, scope: str = "code", facts: Facts = FACTS):
    seat = Burnish(scope=scope)
    return seat.finish(root, "base", facts), seat


def _paths(proposal) -> set[str]:
    return set() if proposal is None else {e.path for e in proposal.edits}


def _block(proposal) -> str:
    new = next(e for e in proposal.edits if e.path.lower().startswith("readme")).new
    return new.split(BEGIN)[1].split(END)[0]


# 1. files the Judge and Warden protect are never touched -----------------------------------------------------

PROTECTED = ["tests/test_a.py", "Tests/test_b.py", "tests/helpers.py", "test/x.py", "testing/y.py", "pkg/test_c.py",
             "pkg/c_test.py", "conftest.py", "pkg/conftest.py", "noxfile.py", ".github/scripts/ci.py",
             ".circleci/gen.py", ".ghost_ledger.py", "pkg/.ghost_x.py", "docs/tests/ex.py"]


@pytest.mark.parametrize("rel", PROTECTED)
def test_a_protected_file_is_never_proposed_even_for_whitespace(tmp_path: Path, rel: str):
    _tree(tmp_path)
    _write(tmp_path, rel)
    proposal, _ = _finish(tmp_path)
    assert rel not in _paths(proposal) and "pkg/ok.py" in _paths(proposal)


def test_burnish_agrees_with_warden_about_what_is_protected(tmp_path: Path):
    _tree(tmp_path)
    for rel in PROTECTED:
        _write(tmp_path, rel)
    proposal, _ = _finish(tmp_path)
    assert not any(is_protected(path) for path in _paths(proposal))


# 2. vendored and generated code is never proposed ------------------------------------------------------------

VENDORED = ["generated/a.py", "extern/b.py", "vendor/c.py", "third_party/d.py", "thirdparty/e.py", "external/f.py",
            "build/g.py", "dist/h.py", "node_modules/i.py", "gen/j.py", "Generated/k.py", "pkg/vendored/l.py"]
BANNERS = ["# @generated\nX = 1   \n", "# autogenerated by tool\nX = 1   \n", "# Auto-generated file\nX = 1   \n",
           "# DO NOT EDIT\nX = 1   \n", "# generated by protoc\nX = 1   \n", "\n\n# this is AutoGenerated code\nX = 1   \n"]


@pytest.mark.parametrize("rel", VENDORED)
def test_a_vendored_or_generated_directory_is_never_proposed(tmp_path: Path, rel: str):
    _tree(tmp_path)
    _write(tmp_path, rel)
    proposal, _ = _finish(tmp_path)
    assert rel not in _paths(proposal)


@pytest.mark.parametrize("banner", BANNERS)
def test_a_generated_banner_in_the_first_ten_lines_is_never_proposed(tmp_path: Path, banner: str):
    _tree(tmp_path)
    _write(tmp_path, "pkg/auto.py", banner)
    proposal, _ = _finish(tmp_path)
    assert "pkg/auto.py" not in _paths(proposal)


def test_a_banner_after_line_ten_does_not_hide_a_file(tmp_path: Path):
    _tree(tmp_path)
    _write(tmp_path, "pkg/late.py", "\n" * 10 + "# generated by hand\nX = 1   \n")
    assert "pkg/late.py" in _paths(_finish(tmp_path)[0])


def test_warden_would_accept_every_edit_burnish_proposes(tmp_path: Path):
    """Warden's own guard is the oracle: no edit is vendored, protected or outside the grant."""
    _tree(tmp_path)
    for rel in (*PROTECTED, *VENDORED):
        _write(tmp_path, rel)
    for banner in BANNERS:
        _write(tmp_path, "pkg/auto.py", banner)
    for scope in ("code", "documentation"):
        proposal, _ = _finish(tmp_path, scope)
        auth = grant("william", "transform", str(tmp_path.resolve()), scope, "test")
        assert violation(tmp_path, proposal, auth) is None
        assert not any(is_vendored(tmp_path, path) for path in _paths(proposal))


def test_a_readme_that_says_it_is_generated_is_not_edited(tmp_path: Path):
    _tree(tmp_path, "<!-- @generated -->\n# demo\n")
    proposal, seat = _finish(tmp_path)
    assert "README.md" not in _paths(proposal)
    assert any("generated" in note for note in seat.notes)


def test_nothing_burnish_writes_looks_generated_to_warden(tmp_path: Path):
    """A short README must not be turned into a 'generated' file by words in the facts handed to Burnish."""
    from warden.models import Defect, DefectSeverity
    hostile = Defect(ghost_id="ghost-1", human_id=None, summary="do not edit: generated by @generated autogenerated",
                     severity=DefectSeverity.MEDIUM, detector="auto-generated")
    facts = Facts(suite=SuiteRun(ran=True, passed=5), remaining=(hostile,), cycles=1)
    _tree(tmp_path, "# demo\n")
    new = next(e for e in _finish(tmp_path, "documentation", facts)[0].edits).new
    head = "\n".join(new.split("\n")[:10]).lower()
    assert not any(m in head for m in ("do not edit", "generated by", "auto-generated", "autogenerated", "@generated"))
    assert not any(m in new.lower() for m in ("do not edit", "generated by", "auto-generated", "autogenerated"))


# 3. a finish that cannot violate the grant -------------------------------------------------------------------

def test_by_default_only_the_readme_is_proposed_because_the_scope_is_unknown(tmp_path: Path, monkeypatch):
    monkeypatch.delenv("BURNISH_SCOPE", raising=False)
    _tree(tmp_path)
    seat = Burnish()
    proposal = seat.finish(tmp_path, "base", FACTS)
    assert _paths(proposal) == {"README.md"}
    assert [e.path for e in seat.code_edits] == ["pkg/ok.py"] and [e.path for e in seat.docs_edits] == ["README.md"]
    assert any("scope=code" in note for note in seat.notes)
    auth = grant("william", "transform", str(tmp_path.resolve()), "documentation", "test")
    assert violation(tmp_path, proposal, auth) is None


def test_the_scope_can_be_given_by_the_environment_or_the_constructor(tmp_path: Path, monkeypatch):
    _tree(tmp_path)
    monkeypatch.setenv("BURNISH_SCOPE", "code")
    assert _paths(Burnish().finish(tmp_path, "base", FACTS)) == {"README.md", "pkg/ok.py"}
    monkeypatch.setenv("BURNISH_SCOPE", "documentation")
    assert _paths(Burnish().finish(tmp_path, "base", FACTS)) == {"README.md"}
    assert _paths(Burnish(scope="code").finish(tmp_path, "base", FACTS)) == {"README.md", "pkg/ok.py"}


def test_the_two_halves_can_be_asked_for_separately(tmp_path: Path):
    _tree(tmp_path)
    assert _paths(Burnish().finish_docs(tmp_path, "base", FACTS)) == {"README.md"}
    assert _paths(Burnish().finish_code(tmp_path, "base", FACTS)) == {"pkg/ok.py"}


def test_the_contract_and_the_api_are_unchanged():
    assert Burnish.requires_contract == "1"
    assert callable(Burnish().finish)


# 4. the report never repeats a claim that Ghost would flag again ---------------------------------------------

STALE = ("# demo\n\n| Project | Tests |\n|---|---|\n| **AUGUR** | 34 tests passing |\n\n"
         "`test_circuit.py` has 16 tests passing, 12 tests collected.\n\n"
         "Sibling projects: herald 390 tests, observe 565 tests. Result: 7 tests passing.\n")


def test_the_block_does_not_contain_a_phrase_ghost_reads_as_a_test_count_claim(tmp_path: Path):
    _tree(tmp_path, STALE + "\nAll 999 tests pass.\n")
    block = _block(_finish(tmp_path, "documentation")[0])
    assert GHOST_TRIGGER.search(block) is None
    assert "999" in block and "disagree" in block


def test_claims_about_other_things_are_counted_but_not_quoted(tmp_path: Path):
    _tree(tmp_path, STALE)
    block = _block(_finish(tmp_path, "documentation")[0])
    assert "Not checked:" in block
    for quoted in ("AUGUR", "test_circuit", "herald", "390", "34"):
        assert quoted not in block


def test_hostile_facts_cannot_put_a_test_count_in_the_block(tmp_path: Path):
    from warden.models import Defect, DefectSeverity
    hostile = Defect(ghost_id="ghost-1", human_id=None, summary="the README claims 135 tests passing, 20 tests.",
                     severity=DefectSeverity.MEDIUM, detector="doc_test_count_drift")
    facts = Facts(suite=SuiteRun(ran=True, passed=5), remaining=(hostile,), cycles=1)
    _tree(tmp_path)
    assert GHOST_TRIGGER.search(_block(_finish(tmp_path, "documentation", facts)[0])) is None


def test_a_disagreement_is_tagged_as_one_not_as_verified(tmp_path: Path):
    _tree(tmp_path, "# demo\n\nAll 999 tests pass.\n")
    block = _block(_finish(tmp_path, "documentation")[0])
    line = next(line for line in block.splitlines() if line.startswith("- README claim"))
    assert "[disagrees]" in line and "verified" not in line.lower()


def test_an_agreement_is_verified_and_an_unmeasured_number_is_unknown(tmp_path: Path):
    _tree(tmp_path, "# demo\n\nThe suite has 5 tests.\n")
    line = next(l for l in _block(_finish(tmp_path, "documentation")[0]).splitlines() if l.startswith("- README claim"))
    assert "[verified]" in line
    none = Facts(suite=SuiteRun(ran=False, reason="no pytest"), remaining=(), cycles=0)
    line = next(l for l in _block(_finish(tmp_path, "documentation", none)[0]).splitlines()
                if l.startswith("- README claim"))
    assert "[unknown]" in line


# 5. markers ---------------------------------------------------------------------------------------------------

INDENTED = f"# demo\n\nExample of the markers:\n\n    {BEGIN}\n    old\n    {END}\n\nAfter.\n"


def test_markers_in_an_indented_code_block_are_examples(tmp_path: Path):
    assert not find_block(INDENTED).found and not find_block(INDENTED).problem
    _tree(tmp_path, INDENTED)
    new = next(e for e in _finish(tmp_path, "documentation")[0].edits).new
    assert new.startswith(INDENTED) and new.count(BEGIN) == 2 and find_block(new).found
    assert find_block(new).start > len(INDENTED)


def test_markers_inside_an_html_comment_are_not_markers():
    text = f"# demo\n\n<!--\n{BEGIN}\nx\n{END}\n-->\n\nend\n"
    assert not find_block(text).found and not find_block(text).problem
    one_line = f"# demo\n\n<!-- see {BEGIN} -->\n"
    assert not find_block(one_line).found


def test_a_heading_inside_a_comment_or_indented_code_is_not_a_heading():
    assert not has_heading("# demo\n\n<!--\n## Claims vs reality\n-->\n", r"claims\s+vs\.?\s+reality")
    assert not has_heading("# demo\n\n    ## Claims vs reality\n", r"claims\s+vs\.?\s+reality")


def test_an_unclosed_comment_at_the_end_does_not_swallow_the_block(tmp_path: Path):
    original = "# demo\n\nIntro.\n\n<!-- todo: write more\n"
    _tree(tmp_path, original)
    proposal, _ = _finish(tmp_path, "documentation")
    new = proposal.edits[0].new
    assert new.startswith(original)
    block = find_block(new)
    assert block.found
    assert "-->" in new[len(original):block.start]
    assert not new[block.start:].lstrip().startswith("-->")
    (tmp_path / "README.md").write_bytes(new.encode("utf-8"))
    assert _finish(tmp_path, "documentation")[0] is None


def test_an_unclosed_comment_holding_an_old_block_gets_a_fresh_visible_one(tmp_path: Path):
    original = f"# demo\n\n<!-- hidden\n{BEGIN}\nold\n{END}\n"
    _tree(tmp_path, original)
    new = _finish(tmp_path, "documentation")[0].edits[0].new
    assert new.startswith(original) and find_block(new).found and find_block(new).start > len(original)


@pytest.mark.parametrize("original", [
    "# demo\n\nIntro.\n\n\n\n", "# demo\n\nIntro.", "# demo\n\nIntro.\n   \n", "# demo\r\n\r\nIntro.\r\n\r\n\r\n",
    "# demo\r\nmixed\nlines\r\nhere\n\n", "# demo\n\nno newline at all, mixed\r\nending"])
def test_the_authors_text_is_kept_byte_for_byte_when_the_block_is_added(tmp_path: Path, original: str):
    _tree(tmp_path, original.encode())
    proposal, _ = _finish(tmp_path, "documentation")
    new = proposal.edits[0].new.encode("utf-8")
    assert new.startswith(original.encode())
    (tmp_path / "README.md").write_bytes(new)
    assert _finish(tmp_path, "documentation")[0] is None


def test_a_mixed_ending_readme_with_a_block_keeps_every_line_ending_when_the_block_changes(tmp_path: Path):
    original = b"# demo\r\nline\nmore\r\n\r\ntail\n"
    _tree(tmp_path, original)
    (tmp_path / "README.md").write_bytes(_finish(tmp_path, "documentation")[0].edits[0].new.encode("utf-8"))
    settled = (tmp_path / "README.md").read_bytes()
    after = settled + b"\nWritten later.\r\n\n"
    (tmp_path / "README.md").write_bytes(after)
    changed = Facts(suite=SuiteRun(ran=True, passed=6), remaining=(), cycles=1)
    new = _finish(tmp_path, "documentation", changed)[0].edits[0].new.encode("utf-8")
    start = after.index(BEGIN.encode())
    assert new.startswith(after[:start]) and new.endswith(b"\nWritten later.\r\n\n")
    assert b"6 passed" in new


def test_a_block_that_ends_the_file_without_a_final_newline_stays_that_way(tmp_path: Path):
    _tree(tmp_path)
    settled = _finish(tmp_path, "documentation")[0].edits[0].new
    bare = settled.rstrip("\n")
    (tmp_path / "README.md").write_bytes(bare.encode("utf-8"))
    changed = Facts(suite=SuiteRun(ran=True, passed=6), remaining=(), cycles=1)
    new = _finish(tmp_path, "documentation", changed)[0].edits[0].new
    assert new.endswith(END) and "6 passed" in new
    (tmp_path / "README.md").write_bytes(new.encode("utf-8"))
    assert _finish(tmp_path, "documentation", changed)[0] is None


# 6. the claim checker only judges claims about this suite -----------------------------------------------------

NOT_CLAIMS = [
    "We added 5 tests for the parser.", "Before the fix, 10 tests failed.", "Tested on Python 3.11 tests included.",
    "Runs under Python 3.11 tests pass on CI.", "We make no claim of 100% coverage.", "It went from 255 to 272 tests.",
    "The goal is 100% coverage.", "herald 390 tests, observe 565 tests.", "There were 30 tests in version 1.",
    "12 unit tests cover the parser.", "Each module has 4 tests per file.", "It has 3 new tests.",
    "Quote: \"135 tests\" was the old claim.", "`test_x.py` has 3 tests.", "We should have 40 tests by June.",
]


@pytest.mark.parametrize("sentence", NOT_CLAIMS)
def test_text_that_is_not_a_claim_about_this_suite_is_not_judged(sentence: str):
    text = f"# demo\n\n{sentence}\n"
    assert claims.test_claims(text) == [] and absolutes(text) == []


@pytest.mark.parametrize("sentence,number,kind", [
    ("The suite has 30 tests.", 30, "count"), ("30 tests passing.", 30, "passing"), ("All 30 tests pass.", 30, "passing"),
    ("30/30 passing.", 30, "passing"), ("Status: 1,234 tests passed.", 1234, "passing"),
    ("Result: 30 automated tests, all green.", 30, "count"), ("30 passing tests.", 30, "passing")])
def test_a_claim_about_this_suite_is_judged(sentence: str, number: int, kind: str):
    found = claims.test_claims(f"# demo\n\n{sentence}\n")
    assert [(c.number, c.kind) for c in found] == [(number, kind)]


def test_all_tests_pass_without_a_number_is_a_claim_about_the_suite():
    green = SuiteRun(ran=True, passed=5)
    red = SuiteRun(ran=True, passed=5, failed=1)
    claim = claims.test_claims("# demo\n\nAll tests pass.\n")[0]
    assert judge(claim, green)[0] and not judge(claim, red)[0]


def test_a_bare_hundred_percent_coverage_is_a_claim_but_a_scoped_one_is_not():
    assert absolutes("# demo\n\nWe have 100% coverage.\n") == ["100% coverage"]
    assert absolutes("# demo\n\n100% coverage of the parser module.\n") == []


def test_skipped_tests_are_not_a_disagreement_unless_the_readme_says_none_are_skipped():
    suite = SuiteRun(ran=True, passed=28, skipped=2)
    ratio = claims.test_claims("# demo\n\n30/30 passing.\n")[0]
    agrees, sentence = judge(ratio, suite)
    assert agrees and "2 skipped" in sentence
    strict = claims.test_claims("# demo\n\n30/30 passing, with no skips.\n")[0]
    assert strict.no_skips and not judge(strict, suite)[0]
    assert not judge(claims.test_claims("# demo\n\n31/31 passing.\n")[0], suite)[0]
    assert not judge(ratio, SuiteRun(ran=True, passed=28, skipped=2, failed=1))[0]


def test_judging_never_writes_the_number_next_to_the_word_tests():
    for suite in (None, SuiteRun(ran=True, passed=5), SuiteRun(ran=True, passed=30)):
        for claim in claims.test_claims("# demo\n\nThe suite has 30 tests. All 12 tests pass.\n"):
            assert GHOST_TRIGGER.search(judge(claim, suite)[1]) is None


def test_mentions_that_are_about_something_else_are_counted():
    text = "# demo\n\n| **AUGUR** | 34 tests passing |\n\n`test_a.py` has 16 tests passing.\n\nherald 390 tests.\n"
    assert unchecked_mentions(text) == 3
    assert claims.test_claims(text) == []


# 7. a compiled README only reads real console scripts --------------------------------------------------------

def test_only_script_tables_are_console_scripts(tmp_path: Path):
    _write(tmp_path, "pkg/__init__.py", '"""d."""\n')
    _write(tmp_path, "pyproject.toml",
           '[project]\nname = "demo"\nversion = "1.0"\n\n[tool.thing]\nkey = "a:b"\nother = "mod:func"\n\n'
           '[project.entry-points."x.y"]\nplugin = "p:q"\n\n[project.scripts]\ndemo = "demo.cli:main"\n')
    assert inspect_tree(tmp_path).scripts == (("demo", "demo.cli:main"),)
    _write(tmp_path, "pyproject.toml", '[tool.poetry]\nname = "d"\n[tool.poetry.scripts]\nrun = "d.cli:go"\n'
                                       '[tool.other]\nx = "m:n"\n')
    assert inspect_tree(tmp_path).scripts == (("run", "d.cli:go"),)


def test_a_settings_line_in_another_table_is_not_listed_in_a_compiled_readme(tmp_path: Path):
    _tree(tmp_path, None)
    _write(tmp_path, "pyproject.toml", '[project]\nname = "demo"\nversion = "0.0.1"\n[tool.x]\nkey = "a:b"\n')
    proposal = Burnish(scope="documentation").finish(tmp_path, "base", FACTS)
    text = next(e for e in proposal.edits if e.path == "README.md").new
    assert "Console scripts: none declared" in text and "a:b" not in text


def test_a_pyproject_that_does_not_parse_still_gives_its_scripts(tmp_path: Path):
    _write(tmp_path, "pyproject.toml", '[project\nname = "demo"\n[tool.x]\nkey = "a:b"\n[project.scripts]\nd = "m:f"\n')
    assert inspect_tree(tmp_path).scripts == (("d", "m:f"),)
